config/routes.rb
Rails.application.routes.draw do
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "promote" => "users#promote", :as => "promote"
  get "demote" => "users#demote", :as => "demote"
  resources :blogposts
  resources :users
  resources :sessions
  root :to => 'blogposts#index'

end

app/models/blogp.rb
# == Schema Information
# Schema version: 20110519140647
#
# Table name: blogps
#
#  id         :integer         not null, primary key
#  entry_text :string(255)
#  user_id    :integer
#  created_at :datetime
#  updated_at :datetime
#

class Blogp < ActiveRecord::Base
  attr_accessible :entry_text, :user_id

#  validates :entry_text,    :presence   =>  true
#  validates :user_id,       :presence   =>  true

end

app/models/blogpost.rb
# == Schema Information
# Schema version: 20110520173756
#
# Table name: blogposts
#
#  id         :integer         not null, primary key
#  title      :string(255)
#  entry_text :text
#  user_id    :integer
#  created_at :datetime
#  updated_at :datetime
#

class Blogpost < ActiveRecord::Base
  belongs_to :user
  validates :title, :presence => true, :length => {:maximum => 255}
  validates :entry_text, :presence => true
  validates :user_id, :presence => true
end

app/models/user.rb
# == Schema Information
# Schema version: 20110520173756
#
# Table name: users
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  email      :string(255)
#  pepper     :string(255)
#  salt       :string(255)
#  user_type  :integer
#  created_at :datetime
#  updated_at :datetime
#

class User < ActiveRecord::Base
  attr_accessible :name, :user_type, :email, :password, :password_confirmation
  attr_accessor :password

  before_save :encrypt_password, :set_user_type

  has_many  :blogposts

  validates :name,      :presence => true,
                        :length => {:maximum => 48}
  validates :email,     :presence => true,
                        :uniqueness => true,
                        :format => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  validates :password,  :presence => true,
                        :confirmation => true

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.pepper == BCrypt::Engine.hash_secret(password, user.salt)
      user
    else
      nil
    end
  end

  private

  def encrypt_password
    if password.present?
      self.salt = BCrypt::Engine.generate_salt
      self.pepper = BCrypt::Engine.hash_secret(password, salt)
    end
  end

  def set_user_type(ut = 0)
    if !User.find_by_user_type(13).nil?
      self.user_type ||= ut
    else
      self.user_type = 13
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/blogposts_controller.rb
class BlogpostsController < JcblogController
  before_filter :authorize, :except => [:index, :show ]
  before_filter :find_blogpost, :except => [:index, :new, :create]

  def index
    @blogposts = Blogpost.all
  end

  def show
    @user = @blogpost.user
  end

  def new
    @user = User.find(session[:user_id])
    @blogpost = @user.blogposts.new
  end

  def create
    @user = User.find(session[:user_id])
    @blogpost = @user.blogposts.new(params[:blogpost])
    if @blogpost.save
      flash[:success] = "Post Saved"
      redirect_to @blogpost
    else
      render :new
    end
  end

  def edit
    @user = @blogpost.user
  end

  def update
    if @blogpost.update_attributes(params[:blogpost])
      flash[:success] = "Changes Saved"
      redirect_to @blogpost
    else
      render :edit
    end
  end

  def destroy
    if @blogpost.delete
      redirect_to blogposts_path
    else
      flash[:error] = "Delete Failed"
      redirect_to @blogpost
    end
  end

  private

  def find_blogpost
    @blogpost = Blogpost.find(params[:id])
    if @blogpost.nil?
      flash[:error] = "Invalid Post"
      redirect_to blogposts_path
    end
  end
end

app/controllers/jcblog_controller.rb
class JcblogController < ApplicationController
  helper_method :admin?
  helper_method :authorize
  helper_method :there_b_admins?
  helper_method :there_b_users?
  helper_method :current_user

  def admin?
    current_user.user_type == 13 if current_user
  end

  def authorize
    if there_b_admins? && !admin?
      redirect_to blogposts_url
    end
  end

  def there_b_admins?
    !User.find_by_user_type(13).nil?
  end

  def there_b_users?
    User.count != 0
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to root_url, :notice => "Logged In"
    else
      flash[:failure] = "Invalid e-Mail or Password"
      redirect_to root_url
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged Out"
  end
end

app/controllers/users_controller.rb
class UsersController < JcblogController
  layout "user_admin"
  before_filter :authorize, :except =>
    [:show, :new, :create, :edit, :update] if :there_b_admins?
  before_filter :find_user, :except =>
    [:index, :new, :create]

  def index
    if there_b_users?
      @users = User.all
    else
      redirect_to sign_up_path
    end
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = 'User Saved'
      redirect_to blogposts_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(params[:user])
      flash[:success] = 'Changes Saved'
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    if @user.delete
      flash[:success] = 'User Deleted'
      redirect_to users_path
    else
      render :show
    end
  end

  def promote
    @user.user_type = 13
    if @user.update_attribute(:user_type, @user.user_type)
      redirect_to @user
    else
      render :show
    end
  end

  def demote
    @user.user_type = 0
    if @user.update_attribute(:user_type, @user.user_type)
      redirect_to @user
    else
      render :show
    end
  end

  private

  def find_user
    @user = User.find(params[:id])
    if @user.nil?
      flash[:error] = 'Invalid User'
      redirect_to users_path
    end
  end
end

app/views/blogposts/_blogpost.html.erb
<h2>
  <%= link_to_unless_current(blogpost.title, blogpost) %>
</h2>
<h4>
  Posted By: <%= blogpost.user.name %>
</h4>
<div>
  <% if admin? %>
    <%= link_to 'Edit', edit_blogpost_path(blogpost) %>
    | <%= link_to 'Delete', blogpost_path(blogpost), :method => :delete %>
    <br />
  <% end %>
  <%= blogpost.entry_text %>
</div>

app/views/blogposts/_form.html.erb
<%= form_for @blogpost do |f| %>
  <% if @blogpost.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @blogpost.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <fieldset>
    <dl>
      <dd><%= f.hidden_field :user_id %></dd>
      <dt><%= f.label :title %></dt>
      <dd><%= f.text_field :title %></dd>
      <dt><%= f.label :entry_text %></dt>
      <dd><%= f.text_area :entry_text %></dd>
    </dl>
  </fieldset>
  <p>
    <%= f.submit 'Save' %>
    <br />
    <%= link_to 'All Blogs', root_path %>
  </p>
<% end %>

app/views/blogposts/edit.html.erb
<%= render 'form', :blogpost => @blogpost %>

app/views/blogposts/index.html.erb
<% if @blogposts.length > 0 %>
  <%= render @blogposts %>
<% else %>
  <br />No Blogs Yet.
<% end %>

app/views/blogposts/new.html.erb
<%= content_for :user_yield do %>
  <%= render @user %>
<% end %>
<%= content_for :blogpost_yield do %>
  <%= render 'form' %>
<% end %>

app/views/blogposts/show.html.erb
<%= render @blogpost %>
<%= link_to 'All Blogs', blogposts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JCBlog</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
  <%= yield :head_yield %>
</head>
<body>
  <div class="contents">
    <%= yield %>
  </div>
</body>
</html>

app/views/layouts/jcblog.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JCBlog</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
  <%= yield :head_yield %>
</head>
<body>
  <div class="flash_msg">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, :class => "flash_#{name}" %>
    <% end %>
  </div>
  <div class="main_nav">
    <% if current_user %>
      <h4>Logged In as: <%= current_user.name %></h4>
      <%= link_to 'Log Out', log_out_path %>
    <% else %>
      <%= link_to 'Sign Up', sign_up_path %>
      <% if there_b_users? %>
        | <%= link_to 'Log In', log_in_path %>
      <% end %>
    <% end %>
    <% if there_b_users? == admin? %>
      | <%= link_to 'User Administration', users_path %>
    <% end %>
    <% if admin? %>
      | <%= link_to 'New Blog', new_blogpost_path %>
    <% end %>
    <% if !there_b_admins? %>
      <br />
      ***There are currently no administrators for this site.***
    <% end %>
  </div>
  <div class="contents">
    <%= yield %>
  </div>
</body>
</html>

app/views/layouts/user_admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JCBlog - User Admin</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
  <%= yield :head_yield %>
</head>
<body>
  <div class="flash_msg">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    <% end %>
  </div>
  <div class="main_nav">
    <%= link_to 'Home', root_path %><br />
    <% if current_user %>
      <h4>Logged In as: <%= current_user.name %></h4>
      <%= link_to 'Log Out', log_out_path %>
    <% else %>
      <%= link_to 'Sign Up', sign_up_path %>
      <% if there_b_users? %>
        | <%= link_to 'Log In', log_in_path %>
      <% end %>
    <% end %>
    <% if !there_b_admins? %>
      <br />
      ***There are currently no administrators for this site.***
    <% end %>
  </div>
  <div class="contents">
    <%= yield %>
  </div>
</body>
</html>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <fieldset>
    <dl>
      <dt><%= f.label :name %></dt>
      <dd><%= f.text_field :name %></dd>
      <dt><%= f.label :email %></dt>
      <dd><%= f.text_field :email %></dd>
      <dt><%= f.label :password %></dt>
      <dd><%= f.password_field :password %></dd>
      <dt><%= f.label :password_confirmation %></dt>
      <dd><%= f.password_field :password_confirmation %></dd>
    </dl>
  </fieldset>
  <p>
    <%= f.submit 'Save' %>
  </p>
<% end %>

app/views/users/_user.html.erb
<h2>
  <%= link_to_unless_current(user.name, user) %>
</h2>
<% if admin? == there_b_admins? %>
  <% if user.user_type == 13 %>
    <span class="highlite_red_yellow">ADMIN</span>
    <%= link_to 'Demote User', demote_path(:id => user) %>
  <% else %>
    <%= link_to 'Promote User', promote_path(:id => user) %>
  <% end %>
  <br />
<% end %>
<%= user.email %>

app/views/users/edit.html.erb
<h2>Edit Account</h2>
<%= render 'form' %>

app/views/users/index.html.erb
<% unless @users.empty? %>
  <%= render 'user', :collection => @users %>
<% end %>

app/views/users/new.html.erb
<h3>
Sign Up
</h3>
<% if !there_b_admins? %>
  There are currently no administrators for this site,
  so you are signing up as one.
<% end %>
<%= render 'form' %>

app/views/users/show.html.erb
<%= render 'user', :user => @user %>
<div id="show_links">
  <% if current_user == @user || admin? %>
    <%= link_to 'Edit User Info', edit_user_path %>
    <% if admin? %>
      | <%= link_to 'All Users', users_path %>
    <% end %>
  <% end %>
</div>